name: climate_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  hive: 
  http:
  flutter_bloc:
  path_provider: 
  cupertino_icons: 
  introduction_screen:
  cached_network_image: 
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/weather_app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/weather_app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: UniformRounded
      fonts:
        - asset: assets/fonts/ur.otf
        - asset: assets/fonts/urbold.otf
        - asset: assets/fonts/urmedium.otf